# Generated by Django 3.2.6 on 2021-09-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_data_storage', '0004_alter_category_name'),
        ('order_data_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime_created',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_data_storage.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products_data_storage.product'),
        ),
    ]
