# Generated by Django 3.2.6 on 2021-09-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_data_storage', '0002_auto_20210905_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='bought_amount',
            new_name='amount',
        ),
    ]
