# Generated by Django 3.2.6 on 2021-09-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_data_storage', '0003_rename_bought_amount_orderitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='order_data_storage.orderstatus'),
        ),
    ]
