# Generated by Django 3.2.6 on 2021-08-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_data_storage', '0002_auto_20210816_1530'),
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='sub_categories',
            field=models.ManyToManyField(to='products_data_storage.Category'),
        ),
        migrations.CreateModel(
            name='MainPageCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('link_to_image', models.URLField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_data_storage.product')),
            ],
        ),
    ]
