# Generated by Django 3.2.6 on 2021-08-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210816_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagecarouselitem',
            name='product',
        ),
    ]
