# Generated by Django 3.2.6 on 2021-08-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_data_storage', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
