# Generated by Django 3.2.6 on 2022-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'Paid'), ('O', 'On the way'), ('D', 'Delivered')], default='C', max_length=2),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
