# Generated by Django 3.2.6 on 2021-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_to_send',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
