# Generated by Django 3.2.6 on 2021-10-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211006_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
