# Generated by Django 3.2.6 on 2021-09-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_image', models.URLField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(null=True)),
                ('amount_remaining', models.PositiveSmallIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('review_text', models.TextField(max_length=1000)),
                ('like', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
