# Generated by Django 3.2.6 on 2021-10-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211006_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link_to_image',
            new_name='img',
        ),
    ]
