# Generated by Django 3.2.6 on 2021-08-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_data_storage', '0002_auto_20210816_1530'),
        ('users_data_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='products_data_storage.Product'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_datetime', models.DateTimeField()),
                ('logged_in_as', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_data_storage.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_data_storage.token')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_data_storage.product')),
            ],
        ),
    ]
